package vfs

func baseQueryActionNames() []string {
	return []string{
		"data-query",
		"base-get",
		"title-resolve",
		"url-resolve",
		"base-block-list",
		"table-list",
		"table-get",
		"record-list",
		"record-get",
		"record-search",
		"record-history-list",
		"field-list",
		"field-get",
		"field-search-options",
		"view-list",
		"view-get",
		"view-get-card",
		"view-get-filter",
		"view-get-group",
		"view-get-sort",
		"view-get-timebar",
		"view-get-visible-fields",
		"dashboard-list",
		"dashboard-get",
		"dashboard-block-list",
		"dashboard-block-get",
		"dashboard-block-get-data",
		"workflow-list",
		"workflow-get",
		"form-list",
		"form-get",
		"form-detail",
		"form-questions-list",
		"role-list",
		"role-get",
	}
}

func baseOpActionNames() []string {
	return []string{
		"advperm-enable",
		"advperm-disable",
		"base-create",
		"base-copy",
		"base-block-create",
		"base-block-delete",
		"base-block-move",
		"base-block-rename",
		"table-create",
		"table-update",
		"table-delete",
		"record-upsert",
		"record-delete",
		"record-batch-create",
		"record-batch-update",
		"record-download-attachment",
		"record-upload-attachment",
		"record-remove-attachment",
		"record-share-link-create",
		"field-create",
		"field-update",
		"field-delete",
		"view-create",
		"view-delete",
		"view-rename",
		"view-set-card",
		"view-set-filter",
		"view-set-group",
		"view-set-sort",
		"view-set-timebar",
		"view-set-visible-fields",
		"dashboard-create",
		"dashboard-update",
		"dashboard-delete",
		"dashboard-arrange",
		"dashboard-block-create",
		"dashboard-block-update",
		"dashboard-block-delete",
		"workflow-create",
		"workflow-update",
		"workflow-enable",
		"workflow-disable",
		"form-create",
		"form-update",
		"form-delete",
		"form-submit",
		"form-questions-create",
		"form-questions-update",
		"form-questions-delete",
		"role-create",
		"role-update",
		"role-delete",
	}
}

func baseQuerySpecs() map[string]actionSpec {
	return plusActionSpecs("base", baseQueryActionNames())
}

func baseActionSpecs() map[string]actionSpec {
	return plusActionSpecs("base", baseOpActionNames())
}
