package vfs

func domainActionSpecs() map[string]map[string]actionSpec {
	return map[string]map[string]actionSpec{
		"approval": {
			"approve":  {args: []string{"approval", "tasks", "approve"}},
			"reject":   {args: []string{"approval", "tasks", "reject"}},
			"transfer": {args: []string{"approval", "tasks", "transfer"}},
			"comment":  {args: []string{"approval", "tasks", "comment"}},
		},
		"base": baseActionSpecs(),
		"calendar": {
			"create": {args: []string{"calendar", "+create"}},
			"rsvp":   {args: []string{"calendar", "+rsvp"}},
		},
		"contact": {
			"search-user": {args: []string{"contact", "+search-user"}},
			"get-user":    {args: []string{"contact", "+get-user"}},
		},
		"docs": {
			"create":            {args: []string{"docs", "+create", "--api-version", "v2"}},
			"update":            {args: []string{"docs", "+update", "--api-version", "v2"}},
			"media-download":    {args: []string{"docs", "+media-download"}},
			"media-insert":      {args: []string{"docs", "+media-insert"}},
			"media-preview":     {args: []string{"docs", "+media-preview"}},
			"media-upload":      {args: []string{"docs", "+media-upload"}},
			"whiteboard-update": {args: []string{"docs", "+whiteboard-update"}},
		},
		"drive": driveActionSpecs(),
		"event": {
			"consume": {args: []string{"event", "consume"}},
			"stop":    {args: []string{"event", "stop"}},
		},
		"im": {
			"chat-create":                 {args: []string{"im", "+chat-create"}},
			"chat-update":                 {args: []string{"im", "+chat-update"}},
			"messages-send":               {args: []string{"im", "+messages-send"}},
			"messages-reply":              {args: []string{"im", "+messages-reply"}},
			"messages-resources-download": {args: []string{"im", "+messages-resources-download"}},
			"reactions":                   {args: []string{"im", "reactions"}},
			"pins":                        {args: []string{"im", "pins"}},
		},
		"mail": {
			"send":            {args: []string{"mail", "+send"}},
			"draft-create":    {args: []string{"mail", "+draft-create"}},
			"draft-edit":      {args: []string{"mail", "+draft-edit"}},
			"draft-send":      {args: []string{"mail", "+draft-send"}},
			"reply":           {args: []string{"mail", "+reply"}},
			"reply-all":       {args: []string{"mail", "+reply-all"}},
			"forward":         {args: []string{"mail", "+forward"}},
			"send-receipt":    {args: []string{"mail", "+send-receipt"}},
			"decline-receipt": {args: []string{"mail", "+decline-receipt"}},
			"share-to-chat":   {args: []string{"mail", "+share-to-chat"}},
			"template-create": {args: []string{"mail", "+template-create"}},
			"template-update": {args: []string{"mail", "+template-update"}},
			"watch":           {args: []string{"mail", "+watch"}},
		},
		"markdown": {
			"create":    {args: []string{"markdown", "+create"}},
			"overwrite": {args: []string{"markdown", "+overwrite"}},
			"patch":     {args: []string{"markdown", "+patch"}},
		},
		"meetings": vcActionSpecs(),
		"minutes": {
			"download":        {args: []string{"minutes", "+download"}},
			"speaker-replace": {args: []string{"minutes", "+speaker-replace"}},
			"update":          {args: []string{"minutes", "+update"}},
			"upload":          {args: []string{"minutes", "+upload"}},
		},
		"okr": {
			"progress-create": {args: []string{"okr", "+progress-create"}},
			"progress-update": {args: []string{"okr", "+progress-update"}},
			"progress-delete": {args: []string{"okr", "+progress-delete"}},
			"upload-image":    {args: []string{"okr", "+upload-image"}},
		},
		"sheets":     sheetsActionSpecs(),
		"slides":     slidesActionSpecs(),
		"tasks":      taskActionSpecs(),
		"vc":         vcActionSpecs(),
		"whiteboard": {"update": {args: []string{"whiteboard", "+update"}}},
		"wiki":       {"node-create": {args: []string{"wiki", "+node-create"}}},
	}
}

func driveActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"upload":              {args: []string{"drive", "+upload"}},
		"download":            {args: []string{"drive", "+download"}},
		"import":              {args: []string{"drive", "+import"}},
		"export":              {args: []string{"drive", "+export"}},
		"export-download":     {args: []string{"drive", "+export-download"}},
		"move":                {args: []string{"drive", "+move"}},
		"delete":              {args: []string{"drive", "+delete"}},
		"add-comment":         {args: []string{"drive", "+add-comment"}},
		"apply-permission":    {args: []string{"drive", "+apply-permission"}},
		"create-folder":       {args: []string{"drive", "+create-folder"}},
		"create-shortcut":     {args: []string{"drive", "+create-shortcut"}},
		"pull":                {args: []string{"drive", "+pull"}},
		"push":                {args: []string{"drive", "+push"}},
		"secure-label-update": {args: []string{"drive", "+secure-label-update"}},
		"sync":                {args: []string{"drive", "+sync"}},
		"task-result":         {args: []string{"drive", "+task_result"}},
		"version-delete":      {args: []string{"drive", "+version-delete"}},
		"version-get":         {args: []string{"drive", "+version-get"}},
		"version-revert":      {args: []string{"drive", "+version-revert"}},
	}
}

func baseActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"advperm-enable":           {args: []string{"base", "+advperm-enable"}},
		"advperm-disable":          {args: []string{"base", "+advperm-disable"}},
		"base-create":              {args: []string{"base", "+base-create"}},
		"base-copy":                {args: []string{"base", "+base-copy"}},
		"base-block-create":        {args: []string{"base", "+base-block-create"}},
		"base-block-delete":        {args: []string{"base", "+base-block-delete"}},
		"base-block-move":          {args: []string{"base", "+base-block-move"}},
		"base-block-rename":        {args: []string{"base", "+base-block-rename"}},
		"table-create":             {args: []string{"base", "+table-create"}},
		"table-update":             {args: []string{"base", "+table-update"}},
		"table-delete":             {args: []string{"base", "+table-delete"}},
		"record-upsert":            {args: []string{"base", "+record-upsert"}},
		"record-delete":            {args: []string{"base", "+record-delete"}},
		"record-batch-create":      {args: []string{"base", "+record-batch-create"}},
		"record-batch-update":      {args: []string{"base", "+record-batch-update"}},
		"record-upload-attachment": {args: []string{"base", "+record-upload-attachment"}},
		"record-remove-attachment": {args: []string{"base", "+record-remove-attachment"}},
		"field-create":             {args: []string{"base", "+field-create"}},
		"field-update":             {args: []string{"base", "+field-update"}},
		"field-delete":             {args: []string{"base", "+field-delete"}},
		"view-create":              {args: []string{"base", "+view-create"}},
		"view-delete":              {args: []string{"base", "+view-delete"}},
		"dashboard-create":         {args: []string{"base", "+dashboard-create"}},
		"dashboard-update":         {args: []string{"base", "+dashboard-update"}},
		"dashboard-delete":         {args: []string{"base", "+dashboard-delete"}},
		"dashboard-arrange":        {args: []string{"base", "+dashboard-arrange"}},
		"workflow-create":          {args: []string{"base", "+workflow-create"}},
		"workflow-update":          {args: []string{"base", "+workflow-update"}},
		"workflow-enable":          {args: []string{"base", "+workflow-enable"}},
		"workflow-disable":         {args: []string{"base", "+workflow-disable"}},
		"form-create":              {args: []string{"base", "+form-create"}},
		"form-update":              {args: []string{"base", "+form-update"}},
		"form-delete":              {args: []string{"base", "+form-delete"}},
		"form-submit":              {args: []string{"base", "+form-submit"}},
		"role-create":              {args: []string{"base", "+role-create"}},
		"role-update":              {args: []string{"base", "+role-update"}},
		"role-delete":              {args: []string{"base", "+role-delete"}},
	}
}

func sheetsActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"workbook-create":       {args: []string{"sheets", "+workbook-create"}},
		"workbook-export":       {args: []string{"sheets", "+workbook-export"}},
		"csv-put":               {args: []string{"sheets", "+csv-put"}},
		"cells-set":             {args: []string{"sheets", "+cells-set"}},
		"cells-batch-clear":     {args: []string{"sheets", "+cells-batch-clear"}},
		"cells-batch-set-style": {args: []string{"sheets", "+cells-batch-set-style"}},
		"cells-clear":           {args: []string{"sheets", "+cells-clear"}},
		"cells-merge":           {args: []string{"sheets", "+cells-merge"}},
		"cells-replace":         {args: []string{"sheets", "+cells-replace"}},
		"cells-set-image":       {args: []string{"sheets", "+cells-set-image"}},
		"cells-set-style":       {args: []string{"sheets", "+cells-set-style"}},
		"cells-unmerge":         {args: []string{"sheets", "+cells-unmerge"}},
		"cols-resize":           {args: []string{"sheets", "+cols-resize"}},
		"rows-resize":           {args: []string{"sheets", "+rows-resize"}},
		"dim-delete":            {args: []string{"sheets", "+dim-delete"}},
		"dim-freeze":            {args: []string{"sheets", "+dim-freeze"}},
		"dim-group":             {args: []string{"sheets", "+dim-group"}},
		"dim-hide":              {args: []string{"sheets", "+dim-hide"}},
		"dim-insert":            {args: []string{"sheets", "+dim-insert"}},
		"dim-move":              {args: []string{"sheets", "+dim-move"}},
		"dim-ungroup":           {args: []string{"sheets", "+dim-ungroup"}},
		"dim-unhide":            {args: []string{"sheets", "+dim-unhide"}},
		"dropdown-delete":       {args: []string{"sheets", "+dropdown-delete"}},
		"dropdown-set":          {args: []string{"sheets", "+dropdown-set"}},
		"dropdown-update":       {args: []string{"sheets", "+dropdown-update"}},
		"filter-create":         {args: []string{"sheets", "+filter-create"}},
		"filter-delete":         {args: []string{"sheets", "+filter-delete"}},
		"filter-update":         {args: []string{"sheets", "+filter-update"}},
		"filter-view-create":    {args: []string{"sheets", "+filter-view-create"}},
		"filter-view-delete":    {args: []string{"sheets", "+filter-view-delete"}},
		"filter-view-update":    {args: []string{"sheets", "+filter-view-update"}},
		"float-image-create":    {args: []string{"sheets", "+float-image-create"}},
		"float-image-delete":    {args: []string{"sheets", "+float-image-delete"}},
		"float-image-update":    {args: []string{"sheets", "+float-image-update"}},
		"pivot-create":          {args: []string{"sheets", "+pivot-create"}},
		"pivot-delete":          {args: []string{"sheets", "+pivot-delete"}},
		"pivot-update":          {args: []string{"sheets", "+pivot-update"}},
		"range-copy":            {args: []string{"sheets", "+range-copy"}},
		"range-fill":            {args: []string{"sheets", "+range-fill"}},
		"range-move":            {args: []string{"sheets", "+range-move"}},
		"range-sort":            {args: []string{"sheets", "+range-sort"}},
		"sheet-copy":            {args: []string{"sheets", "+sheet-copy"}},
		"sheet-create":          {args: []string{"sheets", "+sheet-create"}},
		"sheet-delete":          {args: []string{"sheets", "+sheet-delete"}},
		"sheet-hide":            {args: []string{"sheets", "+sheet-hide"}},
		"sheet-move":            {args: []string{"sheets", "+sheet-move"}},
		"sheet-rename":          {args: []string{"sheets", "+sheet-rename"}},
		"sheet-set-tab-color":   {args: []string{"sheets", "+sheet-set-tab-color"}},
		"sheet-unhide":          {args: []string{"sheets", "+sheet-unhide"}},
		"sparkline-create":      {args: []string{"sheets", "+sparkline-create"}},
		"sparkline-delete":      {args: []string{"sheets", "+sparkline-delete"}},
		"sparkline-update":      {args: []string{"sheets", "+sparkline-update"}},
	}
}

func slidesActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"create":        {args: []string{"slides", "+create"}},
		"media-upload":  {args: []string{"slides", "+media-upload"}},
		"replace-slide": {args: []string{"slides", "+replace-slide"}},
	}
}

func taskActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"create":            {args: []string{"task", "+create"}},
		"update":            {args: []string{"task", "+update"}},
		"assign":            {args: []string{"task", "+assign"}},
		"comment":           {args: []string{"task", "+comment"}},
		"complete":          {args: []string{"task", "+complete"}},
		"reopen":            {args: []string{"task", "+reopen"}},
		"followers":         {args: []string{"task", "+followers"}},
		"reminder":          {args: []string{"task", "+reminder"}},
		"tasklist-create":   {args: []string{"task", "+tasklist-create"}},
		"tasklist-task-add": {args: []string{"task", "+tasklist-task-add"}},
		"subtask":           {args: []string{"task", "subtasks"}},
	}
}

func vcActionSpecs() map[string]actionSpec {
	return map[string]actionSpec{
		"meeting-join":  {args: []string{"vc", "+meeting-join"}},
		"meeting-leave": {args: []string{"vc", "+meeting-leave"}},
		"notes":         {args: []string{"vc", "+notes"}},
		"recording":     {args: []string{"vc", "+recording"}},
	}
}
